import { defineConfig } from 'vitest/config'

/**
 * Vitest replaces `bun test`, which was the only remaining reason to keep Bun
 * on the toolchain. Two behavioural differences drove this configuration:
 *
 * - `bun test` bypassed npm script lifecycle hooks, so CI needed an explicit
 *   `build:grammar` step before the runner started. `yarn test` honours
 *   `pretest`, so the generated grammar is regenerated by the script itself.
 * - The `cli` and `publish-layout` suites shell out to a real build, which is
 *   far slower than the default 5 s per-test timeout allows.
 */
export default defineConfig({
  test: {
    include: ['test/**/*.test.ts'],
    environment: 'node',
    testTimeout: 30_000,
    hookTimeout: 120_000,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov'],
      reportsDirectory: './coverage',
      include: ['src/**/*.ts'],
      // The generated parser is a build artifact, and barrels only re-export.
      exclude: ['src/_grammars/**', 'src/**/index.ts'],
    },
  },
})
