#!/usr/bin/env node
// Precompiles the RFC 4512 Peggy grammar into a plain ES module checked into
// `src/_grammars/`, so the published package never needs to `readFileSync`
// a `.pegjs` file or call `peggy.generate()` at runtime.
//
// Rationale: the previous runtime-generation approach embedded the build
// machine's `__dirname` into the compiled output (see git history), which
// broke every install outside that exact machine, and re-compiled the
// grammar on every `new RFC4512Parser()` call (i.e. on every parsed
// definition, since `parseSchema()` builds a fresh parser each time) —
// thousands of grammar compilations per subschema. Precompiling removes
// both problems: `peggy` becomes a pure devDependency, and the generated
// parser is a plain function.

import peggy from 'peggy'

const { generate } = peggy

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const grammarDir = path.join(__dirname, '../src/_grammars')
const grammarPath = path.join(grammarDir, 'rfc4512.pegjs')
const outputPath = path.join(grammarDir, 'rfc4512.generated.js')
const dtsPath = path.join(grammarDir, 'rfc4512.generated.d.ts')

const grammar = readFileSync(grammarPath, 'utf-8')

const source = generate(grammar, {
  output: 'source',
  format: 'es',
})

const banner = '// AUTO-GENERATED by scripts/build-grammar.mjs — do not edit by hand.\n// Regenerate with `node scripts/build-grammar.mjs` after editing rfc4512.pegjs.\n'

writeFileSync(outputPath, banner + source, 'utf-8')

// Peggy's `output: 'source'` mode doesn't emit type declarations. The
// generated module's exports (`StartRules`, `SyntaxError`, `parse`)
// structurally match peggy's own `Parser` interface, so re-export that
// shape instead of hand-rolling one.
const dts = `${banner}import type { Parser } from 'peggy'

export declare const StartRules: Parser['StartRules']
export declare const SyntaxError: Parser['SyntaxError']
export declare const parse: Parser['parse']
`

writeFileSync(dtsPath, dts, 'utf-8')

console.log(`Generated ${path.relative(process.cwd(), outputPath)} (${source.length} bytes)`)
